version: '3.8'

services:
  backend:
    build:
      context: ./aiAssistant_backend
      dockerfile: Dockerfile
    container_name: ai-assistant-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET:-bXktc3VwZXItc2VjcmV0LWtleS1mb3Itand0LXNlY3JldC1rZXktYXV0aGVudGljYXRpb24=}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-AIzaSyD2YxTN3q9ttP1BTL-RCviBx4hX9UBHB0c}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CORS=DEBUG
    volumes:
      - ./aiAssistant_backend/src/main/resources/serviceAccountKey.json:/app/serviceAccountKey.json:ro
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/auth/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./AiAssistant
      dockerfile: Dockerfile
    container_name: ai-assistant-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./AiAssistant:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge